[build]
  publish = "dist"
  command = "npm run build"
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = false
[build.processing.forms]
  parse = true
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
