site:
  name: Turnkey Leads
  site: 'https://www.turnkeyleads.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M
  
  # Company contact information (used in footer and other components)
  contact:
    email: support@www.turnkeyleads.com
    phone: (123) 456-7890
    address: 981 Route 228, Mars, PA 16046
  
  # Social media links
  social:
    twitter: https://twitter.com/turnkeyleads
    instagram: https://instagram.com/turnkeyleads
    facebook: https://facebook.com/turnkeyleads
    linkedin: https://linkedin.com/company/turnkeyleads

# Default SEO metadata
metadata:
  title:
    default: TurnkeyLeads
    template: '%s — TurnkeyLeads'
  description: "\U0001F680 Real Estate Lead Generation Service"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: TurnkeyLeads
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@example'
    site: '@turnkeyleads'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: G-PY2JMJG02M

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
